---
name: Network Upgrade CosmosSDK
about: Log and track network upgrades
title: 'Network upgrade - {inset network name and version}'
labels: ['NETWORK-UPGRADE', 'NODE-MAINTENANCE']

---

NEEDS REVIEW

- [ ] !!! read release notes !!!
- [ ] build docker image
- [ ] push to dockerhub
- [ ] update nomad jobs
- [ ] run nomad job for one sentry
- [ ] wait for node to finish sync to verify correctness
- [ ] run nomad job for the other sentry
- [ ] run nomad job for relayer nodes

**Done when all nodes are running the new binary and are synced up**
